---
title: "201B Final Project Slides"
author: "Cameron Jones"
date: "17/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}

# Load libraries
suppressMessages(library(tidyverse))
library(tidyverse)
library(RColorBrewer)
library(knitr)
library(lmerTest)

# Load data from data processing 
guesses <- read.csv('../data/guesses_processed.csv')

# Create color palette
paired <- brewer.pal(6, "Paired")
color1 <- paired[1]
color2 <- paired[2]
color3 <- paired[3]

# Create color palette
col.pal <- brewer.pal(6, "Set1")

color.human = col.pal[2]
color.binary = col.pal[3]
color.random = col.pal[1]

color.binary = "green"
color.random = "red"

```

```{r}
# Same calculations with adjusted bounds
guesses.adj <- guesses %>%
  mutate(
    
    # Adjusted lower bound for lazy updating (assuming represents initial lb as 0)
    lowerBound.adj = lowerBound - 1,
    
    # Adjusted upper bound for lazy updating
    upperBound.adj = case_when(
      upperBound == 100 ~ 100,  # No adjustment when U = 100
      TRUE ~ upperBound + 1  # If U has moved, increment by 1 to simulate lazy updating
    ),
    
    # Size measures
    interval = upperBound.adj - lowerBound.adj,
    meanBound = (upperBound.adj + lowerBound.adj) / 2,

    # Subtraction measures
    lb.mod10.0 = lowerBound.adj %% 10 == 0,
    lb.lt.10 = lowerBound.adj < 10,
    sub.borrow = (upperBound.adj %% 10) < (lowerBound.adj %% 10),
    sub.tens.eq = (upperBound.adj %/% 10) == (lowerBound.adj %/% 10),
  
    # Division measures
    interval.odd = (interval %% 2 == 1),
    interval.tens.odd = ((interval %/% 10) %% 2) == 1,
    interval.lt.10 = interval < 10,
  
    # Addition measures
    J = interval / 2,
    add.carry = ((J %% 10) + (lowerBound.adj %% 10)) >= 10,
    j.lt.10 = J < 10,
    j.mod10.0 = (J %% 10) == 0,
  ) %>%
  rowwise() %>%
  mutate(
    # Wrapped measures
    carries = sum(sub.borrow, add.carry, interval.odd, interval.tens.odd),
    ops = (1 - lb.lt.10) + (1 - lb.mod10.0)  + # Subtraction
      (1 - interval.lt.10) + 1 + # Division
      (1 - (j.lt.10 | lb.lt.10)) + (1 - (j.mod10.0 | lb.mod10.0))
    # ops = 6 + sum((-2 * lb.mod10.0), (-2 * lb.lt.10), -j.lt.10, -j.mod10.0, -interval.lt.10)
  )

```


Interval plots

```{r}

p.interval.empty <- guesses.adj %>%
  # group_by(user) %>%
  # mutate(rEIG.user.mean = mean(EIG.relative),
  #        rEIGn = EIG.relative / rEIG.user.mean) %>%
  # group_by(interval) %>%
  # summarise(EIG.relative = mean(EIG.relative)) %>%
  ggplot(aes(interval, EIG.relative)) + 
  # stat_summary(fun.data = "mean_cl_boot", geom = "errorbar", color = color.human,
  #             alpha=0.5, width=0.75) +
  # stat_summary(fun = "mean", geom = "point", color = color.human,
  #              size=1.5, alpha=0.85) + 
  # geom_line(stat="smooth", method = "lm", formula = "y ~ x", se = T,
  #             color="white", alpha=0.85, size=1.5) + 
  theme_minimal() + 
  coord_cartesian(ylim=c(0.5, 1), xlim=c(0, 100), clip="on") +
  labs(
    y = "rEIG",
    x = "Interval Size"
  ) + 
  theme(
      # Text
    panel.background = element_rect(fill = "transparent",colour = NA),
    plot.background = element_rect(fill = "transparent",colour = NA),
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_line(size=0.1, color="#FFFFFFCC"),
    panel.grid.major.x = element_blank(),
    axis.text = element_text(color = "white"),
    text = element_text(color = "white", size=20)
)

p.interval.empty

ggsave("img/interval-empty.png", p.interval.empty, bg = "transparent", width = 10, height = 5)

```

```{r}

p.interval <- guesses.adj %>%
  # group_by(user) %>%
  # mutate(rEIG.user.mean = mean(EIG.relative),
  #        rEIGn = EIG.relative / rEIG.user.mean) %>%
  # group_by(interval) %>%
  # summarise(EIG.relative = mean(EIG.relative)) %>%
  ggplot(aes(interval, EIG.relative)) + 
  stat_summary(fun.data = "mean_cl_boot", geom = "errorbar", color = color.human,
              alpha=0.5, width=0.8) +
  stat_summary(fun = "mean", geom = "point", color = color.human,
               size=1.5, alpha=0.9) + 
  geom_line(stat="smooth", method = "lm", formula = "y ~ x", se = T,
              color="white", alpha=0.85, size=1) + 
  theme_minimal() + 
  coord_cartesian(ylim=c(0.5, 1), xlim=c(0, 100), clip="on") +
  labs(
    y = "rEIG",
    x = "Interval Size"
  ) + 
  theme(
      # Text
    panel.background = element_rect(fill = "transparent",colour = NA),
    plot.background = element_rect(fill = "transparent",colour = NA),
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_line(size=0.1, color="#FFFFFFCC"),
    panel.grid.major.x = element_blank(),
    axis.text = element_text(color = "white"),
    text = element_text(color = "white", size=20)
)

p.interval

ggsave("img/interval.png", p.interval, bg = "transparent", width = 10, height = 5)

```


Midpoint

```{r}

p.midpoint.empty <- guesses.adj %>%
  # group_by(user) %>%
  # mutate(rEIG.user.mean = mean(EIG.relative),
  #        rEIGn = EIG.relative / rEIG.user.mean) %>%
  # group_by(interval) %>%
  # summarise(EIG.relative = mean(EIG.relative)) %>%
  ggplot(aes(meanBound, EIG.relative)) + 
  # stat_summary(fun.data = "mean_cl_boot", geom = "errorbar", color = color.human,
  #             alpha=0.5, width=0.8) +
  # stat_summary(fun = "mean", geom = "point", color = color.human,
  #              size=1.5, alpha=0.9) + 
  # geom_line(stat="smooth", method = "lm", formula = "y ~ x", se = T,
  #             color="white", alpha=0.85, size=1) + 
  theme_minimal() + 
  coord_cartesian(ylim=c(0.6, 1), xlim=c(0, 100), clip="on") +
  labs(
    y = "rEIG",
    x = "Midpoint"
  ) + 
  theme(
      # Text
    panel.background = element_rect(fill = "transparent",colour = NA),
    plot.background = element_rect(fill = "transparent",colour = NA),
    # panel.grid = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_line(size=0.1, color="#FFFFFFCC"),
    panel.grid.major.x = element_blank(),
    axis.text = element_text(color = "white"),
    text = element_text(color = "white", size=20)
)

p.midpoint.empty

ggsave("img/midpoint-empty.png", p.midpoint.empty, bg = "transparent", width = 10, height = 5)

```

```{r}

p.midpoint <- guesses.adj %>%
  # group_by(user) %>%
  # mutate(rEIG.user.mean = mean(EIG.relative),
  #        rEIGn = EIG.relative / rEIG.user.mean) %>%
  # group_by(interval) %>%
  # summarise(EIG.relative = mean(EIG.relative)) %>%
  ggplot(aes(meanBound, EIG.relative)) + 
  stat_summary(fun.data = "mean_cl_boot", geom = "errorbar", color = color.human,
              alpha=0.5, width=0.8) +
  stat_summary(fun = "mean", geom = "point", color = color.human,
               size=1.5, alpha=0.9) + 
  geom_line(stat="smooth", method = "lm", formula = "y ~ x", se = T,
              color="white", alpha=0.85, size=1) + 
  theme_minimal() + 
  coord_cartesian(ylim=c(0.6, 1), xlim=c(0, 100), clip="on") +
  labs(
    y = "rEIG",
    x = "Midpoint"
  ) + 
  theme(
      # Text
    panel.background = element_rect(fill = "transparent",colour = NA),
    plot.background = element_rect(fill = "transparent",colour = NA),
    # panel.grid = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_line(size=0.1, color="#FFFFFFCC"),
    panel.grid.major.x = element_blank(),
    axis.text = element_text(color = "white"),
    text = element_text(color = "white", size=20)
)

p.midpoint

ggsave("img/midpoint.png", p.midpoint, bg = "transparent", width = 10, height = 5)

```

Carries

```{r}

p.carry.empty <- guesses.adj %>%
  # group_by(user) %>%
  # mutate(rEIG.user.mean = mean(EIG.relative),
  #        rEIGn = EIG.relative / rEIG.user.mean) %>%
  # group_by(interval) %>%
  # summarise(EIG.relative = mean(EIG.relative)) %>%
  ggplot(aes(carries, EIG.relative)) + 
  # stat_summary(fun.data = "mean_cl_boot", geom = "errorbar", color = color.human,
  #             alpha=0.5, width=0.8) +
  # stat_summary(fun = "mean", geom = "point", color = color.human,
  #              size=1.5, alpha=0.9) + 
  # geom_line(stat="smooth", method = "lm", formula = "y ~ x", se = T,
  #             color="white", alpha=0.85, size=1) + 
  theme_minimal() + 
  coord_cartesian(ylim=c(0.6, 1), xlim=c(0, 4), clip="on") +
  labs(
    y = "rEIG",
    x = "No. Carries"
  ) + 
  theme(
      # Text
    panel.background = element_rect(fill = "transparent",colour = NA),
    plot.background = element_rect(fill = "transparent",colour = NA),
    # panel.grid = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_line(size=0.1, color="#FFFFFFCC"),
    panel.grid.major.x = element_blank(),
    axis.text = element_text(color = "white"),
    text = element_text(color = "white", size=20)
)

p.carry.empty

ggsave("img/carry-empty.png", p.carry.empty, bg = "transparent", width = 10, height = 5)

```

```{r}

p.carry <- guesses.adj %>%
  # group_by(user) %>%
  # mutate(rEIG.user.mean = mean(EIG.relative),
  #        rEIGn = EIG.relative / rEIG.user.mean) %>%
  # group_by(interval) %>%
  # summarise(EIG.relative = mean(EIG.relative)) %>%
  ggplot(aes(carries, EIG.relative)) + 
  stat_summary(fun.data = "mean_cl_boot", geom = "errorbar", color = color.human,
              alpha=0.5, width=0.075) +
  stat_summary(fun = "mean", geom = "point", color = color.human,
               size=1.5, alpha=0.9) + 
  geom_line(stat="smooth", method = "lm", formula = "y ~ x", se = T,
              color="white", alpha=0.85, size=1) + 
  theme_minimal() + 
  coord_cartesian(ylim=c(0.6, 1), xlim=c(0, 4), clip="on") +
  labs(
    y = "rEIG",
    x = "No. Carries"
  ) + 
  theme(
      # Text
    panel.background = element_rect(fill = "transparent",colour = NA),
    plot.background = element_rect(fill = "transparent",colour = NA),
    # panel.grid = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_line(size=0.1, color="#FFFFFFCC"),
    panel.grid.major.x = element_blank(),
    axis.text = element_text(color = "white"),
    text = element_text(color = "white", size=20)
)

p.carry

ggsave("img/carry.png", p.carry, bg = "transparent", width = 10, height = 5)

```